### PR TITLE
FLOATY FLOATY FORK

### PR DESCRIPTION
**Pull request by DeltaNedas**
Right so valkyrium ore.
It drops 4-8 valkyrium shards without fortune and more with it.
It has no anti gravity effect which is odd considering shards are less concentrated but do.
Introducing.

FLOATY FLOATY FORK
please merge

### CODE REVIEW

**Comment by DeltaNedas** [comment]
jesus look at commit messages im a mess

**Comment by Rubydesic** [comment]
no one merge without squashing this

**Comment by DeltaNedas** [comment]
agreed

**Comment by DeltaNedas** [comment]
what the fuck

**Comment by DeltaNedas** [comment]
boat, manually merged

**Pull request closed without merging**
