### PR TITLE
Rename config and some options

### PR DESCRIPTION
**Pull request by tie**
- Renames the config file from `Valkyrien Skies.cfg` to `valkyrienskies.cfg` to be consistent with other mods.
- Renames some config options and adds pretty names and tooltips using language files.

Note that this is a breaking change. Since VS is still considered unstable I did not provide any migration scheme. Let me know if you still insist on adding it.

### CODE REVIEW

**Comment by Rubydesic** [comment]
If you want to merge a breaking change into master and not breaking/1.0 it would be preferable to have a migration scheme.

Let me know if you need help implementing one.

**Comment by tie** [comment]
What’s the purpose of breaking/1.0 branch and is the feature set different from master? Didn’t find any doc on this.

**Comment by Rubydesic** [comment]
breaking/1.0 does in fact have a different feature-set from master, it's where we make all of our breaking changes.

**Comment by tie** [comment]
So the next release will be based breaking branch? If the branch is breaking, are you planning on adding compatibility with existing worlds later?

Anyway, if the actual development happens on breaking/1.0, I’d rather rebase changes because it’d be easier to merge with master later.

Thanks for offering help, I think I can handle implementing the migration. Manually reading old config on load and assigning values to VSConfig fields should work fine.

**Comment by Rubydesic** [comment]
Breaking branch is for our 1.0 version which will not be backwards compatible

**Comment by Tri0de** [comment]
Merged, lets hope it works.

**Pull request merged**
